from app.execution.models import ExecutionResult


class ExecutionEngine:
    """
    Executes plans generated by the planner.
    """

    def __init__(self, skill_manager, context):
        self.skill_manager = skill_manager
        self.context = context

    def execute(self, plan):

        results = []

        for step in plan:

            intent = step.get("intent", "")

            # Update context
            self.context.set_last_tool(intent)

            if intent == "open_application":
                self.context.set_application(step.get("target"))

            response = self.skill_manager.execute(step)

            results.append(
                ExecutionResult(
                    success=True,
                    message=response,
                    step=step,
                )
            )

        return results